package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	graphql1 "graphql-api/domain/models/graphql"
	graphql2 "graphql-api/infrastructure/graphql"
)

// CreateComment is the resolver for the CreateComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, params graphql1.CreateCommentInput) (*graphql1.CommentDetail, error) {
	return r.CommentUsecase.Create(ctx, params)
}

// UpdateComment is the resolver for the UpdateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, params graphql1.UpdateCommentInput) (*graphql1.CommentDetail, error) {
	return r.CommentUsecase.Update(ctx, params)
}

// Comment is the resolver for the Comment field.
func (r *queryResolver) Comment(ctx context.Context, id int64) (*graphql1.CommentDetail, error) {
	return r.CommentUsecase.Fetch(ctx, id)
}

// Mutation returns graphql2.MutationResolver implementation.
func (r *Resolver) Mutation() graphql2.MutationResolver { return &mutationResolver{r} }

// Query returns graphql2.QueryResolver implementation.
func (r *Resolver) Query() graphql2.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
