package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
	graphql1 "graphql-api/domain/models/graphql"
)

// CreateStaff is the resolver for the CreateStaff field.
func (r *mutationResolver) CreateStaff(ctx context.Context, params graphql1.StaffCreateInput) (*graphql1.StaffDetail, error) {
	panic(fmt.Errorf("not implemented: CreateStaff - CreateStaff"))
}

// UpdateStaff is the resolver for the UpdateStaff field.
func (r *mutationResolver) UpdateStaff(ctx context.Context, params graphql1.StaffUpdateInput) (*graphql1.StaffDetail, error) {
	panic(fmt.Errorf("not implemented: UpdateStaff - UpdateStaff"))
}

// Staff is the resolver for the Staff field.
func (r *queryResolver) Staff(ctx context.Context, id int64) (*graphql1.StaffDetail, error) {
	panic(fmt.Errorf("not implemented: Staff - Staff"))
}
