package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	graphql1 "graphql-api/domain/models/graphql"
	graphql2 "graphql-api/infrastructure/graphql"
)

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, id int) (*graphql1.UserDetail, error) {
	panic(fmt.Errorf("not implemented: User - User"))
}

// Query returns graphql2.QueryResolver implementation.
func (r *Resolver) Query() graphql2.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
