package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	graphql1 "graphql-api/domain/models/graphql"
	graphql2 "graphql-api/infrastructure/graphql"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, params graphql1.CreateUserInput) (*graphql1.UserDetail, error) {
	return r.UserUsecase.Create(ctx, params)
}

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, params graphql1.UpdateUserInput) (*graphql1.UserDetail, error) {
	return r.UserUsecase.Update(ctx, params)
}

// DeleteUser is the resolver for the DeleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int64) (*graphql1.UserDetail, error) {
	return r.UserUsecase.Delete(ctx, int64(id))
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, id int64) (*graphql1.UserDetail, error) {
	return r.UserUsecase.Fetch(ctx, int64(id))
}

// Posts is the resolver for the posts field.
func (r *userDetailResolver) Posts(ctx context.Context, obj *graphql1.UserDetail) ([]*graphql1.PostDetail, error) {
	return r.PostUsecase.FetchByUserID(ctx, obj.ID)
}

// UserDetail returns graphql2.UserDetailResolver implementation.
func (r *Resolver) UserDetail() graphql2.UserDetailResolver { return &userDetailResolver{r} }

type userDetailResolver struct{ *Resolver }
