services:
  db-test-local:
    container_name: 'test-postgres'
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=graphql-api-user
      - POSTGRES_DB=graphql-api-db-test
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432