// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateUserInput struct {
	Name string `json:"Name"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	ID   int64  `json:"ID"`
	Name string `json:"Name"`
}

type UserDetail struct {
	ID   int64  `json:"ID"`
	Name string `json:"Name"`
}
